CREATE TABLE IF NOT EXISTS comment (
    _id INTEGER PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id INTEGER NOT NULL,
    body TEXT NOT NULL DEFAULT "",
    FOREIGN KEY(user_id) REFERENCES user(_id)
);